Update tracing and error handling
magieno/pristine-ts pull request #42
Opened 2021-05-25 22:09 UTC by etiennenoel

2021-05-25 22:48 UTC, mathieugh requested changes

2021-05-25 22:48 UTC, mathieugh commented on packages/core/src/interceptors/event-logging.interceptor.ts
> +        this.logHandler.info("New raw event received", event);
Je pense que c'est l'inverse ?

2021-05-25 22:59 UTC, etiennenoel commented on packages/core/src/interceptors/event-logging.interceptor.ts
> +        this.logHandler.info("New raw event received", event);
Effectivement.

2021-05-26 14:39 UTC, mathieugh approved these changes

2021-05-26 14:39 UTC, merged