First round of cli features completed.
magieno/pristine-ts pull request #556
Opened 2023-04-16 23:19 UTC by etiennenoel

2023-08-28 16:03 UTC, mathieugh requested changes

2023-08-28 16:03 UTC, mathieugh commented on packages/validation/src/interceptors/body-validation.request-interceptor.ts
> +        const mappedBody = plainToInstance(methodNode.route.context.bodyValidator.classType, request.body);
What's the difference here ?

2023-08-28 16:03 UTC, mathieugh commented on tests/cli/src/launch-command.scenario.e2e.ts
> +        // todo: make sure the help and list commands can be successfully launched.
This does not seem to be done ?

2023-08-28 16:03 UTC, mathieugh commented on tests/e2e/scenarios/modules/cli/sample.command.js
Do we want to commit the JS file ?

2023-08-28 21:34 UTC, etiennenoel commented on packages/validation/src/interceptors/body-validation.request-interceptor.ts
> +        const mappedBody = plainToInstance(methodNode.route.context.bodyValidator.classType, request.body);
plainToClass is deprecated

2023-08-28 22:56 UTC, etiennenoel commented on packages/cli/readme.md
> +# How to use
Done.

2023-08-28 23:05 UTC, etiennenoel commented on tests/cli/src/launch-command.scenario.e2e.ts
> +        // todo: make sure the help and list commands can be successfully launched.
Done.

2023-08-29 15:57 UTC, mathieugh approved these changes

2023-08-29 16:13 UTC, merged