- Created the FileResolver.
magieno/pristine-ts pull request #717
Opened 2024-07-06 21:52 UTC by etiennenoel

2024-07-08 19:55 UTC, mathieugh requested changes

2024-07-08 19:55 UTC, mathieugh commented on packages/file/src/resolvers/file.resolver.spec.ts
> +        expect(fileResolver.resolve()).rejects.toThrow();//new ConfigurationResolverError("The file doesn't exist.", filename));
Why the comment at the end ?

2024-07-08 19:55 UTC, mathieugh commented on packages/validation/package-lock.json
Why did this one get changed ?

2024-07-09 03:00 UTC, etiennenoel commented on packages/validation/package-lock.json
I ran npm install at some point because I thought I needed this module.

2024-07-09 03:01 UTC, etiennenoel commented on packages/file/src/resolvers/file.resolver.spec.ts
> +        expect(fileResolver.resolve()).rejects.toThrow();//new ConfigurationResolverError("The file doesn't exist.", filename));
Oops, removed.

2024-07-09 13:30 UTC, mathieugh approved these changes

2024-07-09 15:22 UTC, merged