- Added options mapper
magieno/pristine-ts pull request #98
Opened 2021-08-17 14:16 UTC by mathieugh

2021-08-17 15:28 UTC, etiennenoel requested changes

2021-08-17 15:28 UTC, etiennenoel commented on packages/core/src/interfaces/options-mapper.interface.ts
> +    reverseMap(options: Options, onObject?: Model): Promise<Model>;
Model ça existe?

2021-08-17 15:42 UTC, mathieugh commented on packages/core/src/interfaces/options-mapper.interface.ts
> +    reverseMap(options: Options, onObject?: Model): Promise<Model>;
C'est l'equivalent de mettre <T, E> c'est juste que c'est plus clair

2021-08-17 20:45 UTC, etiennenoel commented on packages/core/src/interfaces/options-mapper.interface.ts
> +    reverseMap(options: Options, onObject?: Model): Promise<Model>;
OHH. ça prendrait aussi une fonction `map` qui est l'inverse.

2021-08-18 15:40 UTC, etiennenoel approved these changes

2021-08-18 16:09 UTC, merged